#!/bin/sh
set -e

# Helpers
# =========
USAGE="$0 [expose|hide] [git repository permissions group (username)]"
nginx_config_file="/usr/pkg/etc/nginx/$username"

usage() {
  echo $USAGE
  exit 1
}

write_nginx_config() {
  username="$1"
}

# Receive input
# =========
cmd="$1"
username="$2"

# Check input 
# =========
test "$cmd" = expose || test "$cmd" = hide || usage # valid command?
finger "$username" > /dev/null || usage             # valid user?

# Run
# =========
if test "$cmd" = hide; then
  rm "$nginx_config_file"
elif test "$cmd" = expose; then
  write_nginx_config > "$nginx_config_file"
fi
